Pull request for desktop version, add csss ad html code with styles and sizing
TechnoAndy/My-Portfolio pull request #5
Opened 2022-08-26 07:17 UTC by TechnoAndy

2022-08-26 21:18 UTC, mahbubul14 requested changes
Hi @TechnoAndy ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Your current readme file is not professional enough. Kindly add the getting started section. This should be an example of how you may give instructions on setting up your project locally and also update the author section properly. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title.

### Optional suggestions

- [ ] Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-26 21:18 UTC, mahbubul14 commented on index.html
> +                  <img src="images/SnapshootPortfolio02.png" alt="" />
- [x] Kindly change the background color of this section to match the Figma design. :+1: 

- [x] Please adjust the margin and padding of the image to match the Figma design. :+1: 

- [x] Kindly reduce the gap between the content and image of this section. :+1: 

- [x] You should change the font color and weight to match with the Figma design. (ex: project descriptions, technologies, see project button). :+1: 

- [x] The "See Project" button should take you to the Live Demo of the project or to the GitHub repository. Kindly work on it. :+1: 

Your design            
:-------------------------:
![Screenshot from 2022-08-27 02-25-24](https://user-images.githubusercontent.com/70483835/186985530-edbf4981-d3c9-46ee-a2b2-69188787e42a.png)


|  Figma Design
|:-------------------------:

![Screenshot from 2022-08-27 02-28-09](https://user-images.githubusercontent.com/70483835/186985759-03453c67-6fcd-4e0b-8ec0-4ef4d955c587.png)

2022-08-26 21:18 UTC, mahbubul14 commented on index.html
> +                    <h2 class="header-text">About<br>Myself</h2>
- [x] You should reduce the gap between the left and right blocks of this section. :+1: 

- [x] Your current design for the right block doesn't match with the Figma design. Kindly increase the gap between the dropdown menu and experiences. :+1: 

Your design  
:-------------------------:
![Screenshot from 2022-08-27 02-41-21](https://user-images.githubusercontent.com/70483835/186987972-76feeefe-056f-4e1f-947f-0d2455e9f43f.png)

Figma Design
|:-------------------------:
![Screenshot from 2022-08-27 02-45-21](https://user-images.githubusercontent.com/70483835/186988141-9fc14a21-0931-404a-aedd-dc8cafcfb0b1.png)

2022-08-27 00:58 UTC, tugsem approved these changes
Hi  @TechnoAndy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/3o6Ztp6SgDdzR0XD2w/giphy.gif)

## Highlights ⭐ 
✅ You have applied requested changes
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 01:13 UTC, merged